<?php

namespace App\Imports;

use App\Models\MniData;
use App\Models\NrMniData;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class DataImport implements ToModel, WithHeadingRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new NrMniData([
            'compname'=> $row['compname'],
            'akadba'=> $row['akadba'],
            'physaddr'=> $row['physaddr'],
            'physcity'=> $row['physcity'],
            'physstate'=> $row['physstate'],
            'physzip'=> $row['physzip'],
            'vnumber'=> $row['vnumber'],
            'loccount'=> $row['loccount'],
            'products'=> $row['products'],
            'exec1'=> $row['exec1'],
            'gender1'=> $row['gender1'],
            'officermail1'=> $row['officermail1'],
            'title1'=> $row['title1'],
            'exec2'=> $row['exec2'],
            'gender2'=> $row['gender2'],
            'officermail2'=> $row['officermail2'],
            'title2'=> $row['title2'],
            'fnumber'=> $row['fnumber'],
            'nnumber'=> $row['nnumber'],
            'web'=> $row['web'],
            'email'=> $row['email'],
            'mailaddr'=> $row['mailaddr'],
            'mailcity'=> $row['mailcity'],
            'mailstate'=> $row['mailstate'],
            'mailzip'=> $row['mailzip'],
            'yearestab'=> $row['yearestab'],
            'distribtyp'=> $row['distribtyp'],
            'ownertype'=> $row['ownertype'],
            'sales'=> $row['sales'],
            'squarefeet'=> $row['squarefeet'],
            'imports'=> $row['imports'],
            'exec3'=> $row['exec3'],
            'gender3'=> $row['gender3'],
            'officermail3'=> $row['officermail3'],
            'title3'=> $row['title3'],
            'exec4'=> $row['exec4'],
            'gender4'=> $row['gender4'],
            'officermail4'=> $row['officermail4'],
            'title4'=> $row['title4'],
            'exec5'=> $row['exec5'],
            'gender5'=> $row['gender5'],
            'officermail5'=> $row['officermail5'],
            'title5'=> $row['title5'],
            'exec6'=> $row['exec6'],
            'gender6'=> $row['gender6'],
            'officermail6'=> $row['officermail6'],
            'title6'=> $row['title6'],
            'exec7'=> $row['exec7'],
            'gender7'=> $row['gender7'],
            'officermail7'=> $row['officermail7'],
            'title7'=> $row['title7'],
            'exec8'=> $row['exec8'],
            'gender8'=> $row['gender8'],
            'officermail8'=> $row['officermail8'],
            'title8'=> $row['title8'],
            'exec9'=> $row['exec9'],
            'gender9'=> $row['gender9'],
            'officermail9'=> $row['officermail9'],
            'title9'=> $row['title9'],
            'exec10'=> $row['exec10'],
            'gender10'=> $row['gender10'],
            'officermail10'=> $row['officermail10'],
            'title10'=> $row['title10'],
            'parentname'=> $row['parentname'],
            'parentcity'=> $row['parentcity'],
            'parentstate'=> $row['parentstate'],
            'onumber'=> $row['onumber'],
            'header'=> $row['header'],
            'advertiser'=> $row['advertiser'],
            'primarysic'=> $row['primarysic'],
            'sic2'=> $row['sic2'],
            'companyid'=> $row['companyid'],
            'datasource'=> $row['datasource'],
            'bookid'=> $row['bookid'],
            'newinyear'=> $row['newinyear'],
            'priority'=> $row['priority'],
            'addresserror'=> $row['addresserror'],
            'dpvfootnote'=> $row['dpvfootnote'],
            'altphone'=> $row['altphone'],
            'paddress'=> $row['paddress'],
            'pzip5'=> $row['pzip5'],
            'filesNamePath'=> 1,
            'filesName'=> 1,
            'exec11'=> $row['exec11'],
            'gender11'=> $row['gender11'],
            'officermail11'=> $row['officermail11'],
            'title11'=> $row['title11'],
            'exec12'=> $row['exec12'],
            'gender12'=> $row['gender12'],
            'officermail12'=> $row['officermail12'],
            'title12'=> $row['title12'],
            'exec13'=> $row['exec13'],
            'gender13'=> $row['gender13'],
            'officermail13'=> $row['officermail13'],
            'title13'=> $row['title13'],
            'exec14'=> $row['exec14'],
            'gender14'=> $row['gender14'],
            'officermail14'=> $row['officermail14'],
            'title14'=> $row['title14'],
            'exec15'=> $row['exec15'],
            'gender15'=> $row['gender15'],
            'officermail15'=> $row['officermail15'],
            'title15'=> $row['title15'],
            'CutDate'=> 1
        ]);
    }
}
